import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import Navbar from "@/components/Navbar";
// import { Geist, Geist_Mono } from "next/font/google";
import  ReactQueryProvider from "@/lib/react-query";
import "./globals.css";
import Footer from "@/components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <Navbar />
          <ReactQueryProvider>{children}</ReactQueryProvider>
          <Footer />
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
